name: optimized_gesture_detector
description: An optimized class on flutter GestureDetector
version: 1.4.0
homepage: https://github.com/SunPointed/OptimizedGestureDetector

environment:
  sdk: '>=3.10.8 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
